### ISSUE TITLE
Saving a model after fitting

### ISSUE THREAD

**Issue by skrish13** [EvgenyNekrasov/gpod#1]
Do we need a ".dump()" or ".save()" method for better user interface? As of now I guess people can just pickle/hickle it and load it to use again basically?

**Comment by EvgenyNekrasov** [comment]
Due to gpod uses external classifier ".save" method may not work correctly for some cases e.g. if your classifier dumps some data on disc. You can use pickle in most cases. The following code can help you to save and load detectors with pickle:
```python
import pickle
import zlib

def save_obj(obj, fl):
    obj2 = pickle.dumps(obj, protocol=3)
    obj3 = zlib.compress(obj2, 6)
    f = open(fl, 'wb')
    f.write(obj3)
    f.close()


def load_obj(fl):
    f = open(fl, 'rb')
    obj3 = f.read()
    f.close()
    obj2 = zlib.decompress(obj3)
    obj = pickle.loads(obj2)
    return obj
```

**Comment by skrish13** [comment]
Hmm okay, thanks!
